export const ApiConstants = {
  LiveCasinoGame: "/mac88/casino/list",
  LiveCasinoGameLogin: "/mac88/casino/login",
  LiveCasinoGameProvider: "/mac88/providers",
  LiveCasinoGameBets: "/mac88/bets",
  AUTH: {
    LOGIN: "/auth/login",
    LOGOUT: "/auth/logout",
    CHANGEPASSWORD: "user/changePassword",
    OLD_PASSWORD: "/user/check/oldPassword",
  },
  MATCH: {
    RATES: "/getUserRateDetails/",
    MATCHLIST: "/match/list",
    SEARCHLIST: "/user/searchlist",
    MATCHDETAILS: "/match/",
    CURRENTBET: "/bet",
    MARKET_MATCH_LIST_CRICKET:
      "https://marketsarket.qnsports.live/getcricketmatches",
    MARKET_MATCH_LIST_FOOTBALL:
      "https://marketsarket.qnsports.live/getsoccerallmatches2",
    MARKET_MATCH_LIST_TENNIS:
      "https://marketsarket.qnsports.live/gettennisallmatches2",
  },
  USER: {
    MARQUEE: "/expert/notification",
    SET_BTN_VALUE: "/button/insert",
    GET_BTN_VALUE: "/button",
    GET_PROFILE: "/user/profile",
    ACCOUNT_STATEMENT: "/transaction/get/",
    LIST: "/user/list",
    MATCH_WISE_PROFITLOSS: "user/total/matchWise/profitLoss",
    TOTAL_PROFITLOSS: "user/totalProfitLoss",
    TOTAL_BET_PROFITLOSS: "user/total/bet/profitLoss",
    TOTAL_SESSION_PROFITLOSS: "user/total/session/profitLoss",
  },
  EXPERT: {
    COMPETITIONLIST: "/expert/match/competitionList/",
    COMPETITIONDATES: "/expert/match/competition/dates/",
    COMPETITIONMATCHES: "/expert/match/competition/getMatch/",
  },
  CARDS: {
    MATCH: {
      GET_CARD_DETAIL: "/match/card",
      GET_CARD_DETAIL_INITIAL: "/match/initial/card",
      PLACE_BET: "/bet/cardBetting",
      RESULT: "/card/result/detail",
    },
  },
  BET: {
    PLACEBETSESSION: "bet/session",
    PLACEBETMATCHBETTING: "bet/matchBetting",
    PLACEBETTOURNAMENT: "bet/tournament",
    GETPLACEDBETS: "bet",
    RUN_AMOUNT: "bet/session/profitLoss",
    BET_ACCOUNTSTATEMENT: "bet/accountStatement",
  },
  LIVESTREAM: {
    GET_CHANNEL_ID: "https://scoreapi.365cric.com/api/match/getStream",
    GET_VIDEO: "https://video.proexch.in/tv/static",
  },
};

export const Constants = {
  pageLimit: 10,
  AuthPaths: {
    root: "/",
    login: "login",
    changePassword: "change-password",
  },

  MainPaths: {
    root: "/",
    match: "match",
    comingSoon: "comingsoon",
    liveMarketMatches: "inplay/matchDetail",
    liveMarketSport: "match/matchDetail",
    myAccount: "my-account",
    liveMarket: "inplay",
    changeButtonValue: "my-account/change_button_value",
    rules: "rules",
    changePassword: "my-account/change_password",
    secureAuth: "my-account/secure-auth",
    liveCasino: "liveCasino",
    casino: "casino",
    crashGames: "crashGames",
    macVirtual: "macVirtual",
    coloPred: "colorPred",
    macExcite: "macExcite",
  },
  ReportsPaths: {
    root: "/",
    profitLoss: "my-account/profit_loss",
    accountStatement: "my-account/account_statement",
    currentBet: "my-account/current_bet",
    generalReport: "my-account/general_report",
    betHistory: "my-account/bet_history",
  },
  pageCount: 10,
  listOfClientCountLimit: 15,

  // customPageLimit: 10,
  // customTimeOut: 300000,// 5 mint in mili seconds user ideal 5 mint after that logout
  // customTimer: 30000,// 30 sec in mili seconds remainint timer start and show message  Your session will expire in 30 second
  // sessionExpireTime: 30 // 30 sec,

  customPageLimit: 15,
  customTimeOut: 1000 * 60 * 60, // 5 mint in mili seconds user ideal 5 mint after that logout
  customTimer: 1000 * 60 * 5, // 30 sec in mili seconds remainint timer start and show message  Your session will expire in 30 second
  sessionExpireTime: 60 * 5, // 30 sec
  apiBasePath: "https://devbetfairapi.fairgame.club",
  thirdParty: "https://devserviceapi.fairgame.club",
  expertPath: "https://devexpertapi.fairgame.club",
  apiBasePathLive: "https://betfairapi.fairgame7.com",
  thirdPartyLive: "https://serviceapi.fairgame7.com",
  expertPathLive: "https://expertapi.fairgame7.com",
  localPath: "http://localhost:5000",
  localPathThird: "http://localhost:3200",
  localPathExpert: "http://localhost:6060",
  WEBSOCKET: "websocket",
  POLLING: "polling",
  PRODUCTION: "production",
  randomeNumber: "JiskaPataNaLageG",
  publicNumber: `U2FsdGVkX1+7Lz0LzD8AsrBoHiQrViZiWhIWBqYuL4dgfGXwUbjJndfELn+Usn4xpSEl8s1RoIqzSS/EHUfPLYK/iq/6V0lKQpDaaK52maKES7/cOdFiuXYTVTGu+/HajYeHTly+Xgn1egPHG1NcK9wP6U3vTUDEkHaB2C4hNejgB/JPzdDD8pp60kc+VzCrkbxbRM2oiR4iEtCRQPac4vz0SdQFaSPaG1gexmBFdu/w5ZMSPoPxuSM2rSA0UvmYobUoP5VkQbkIlL1fZhlwOmJ2bm5AHUyfzfHU1njCgwYhB6eJswzg0Qr8lu2cstCaB6zmxeXmdYF41o157foAyeXgBT/TRYt4nwFQ4WuKngLRPPjM6/LD/sY9sZBFv58i`,
  privateNumber: `U2FsdGVkX19PB0k7pc6tsaolSzWPHY2kgJvHhevrMQ7JuPxXzoTJ/RVKBD6yBUt3xnPx4Nu+beP2YSbQ5GvSxw0ZJRzPMDNp1UOtOPzl5afvOf2wbvZLzhHSkW/qUmERYHLa7b24YLZDY0nIjS6PRLxc22qlRavxSa0/LCRGN0tWmTneiwD6aCgYPkD6YyzpL7qhBPCPSzCJ4CG05wknMfhg6kZSfNEYssJy3moQdlNTjr/6H923TMHCyE5GNfXeLgEYFdA2xxfbRiDJNvm9oJeDyhOiKOqM5kw7GceZQ4pHbtd4snOkfrMjVCY+ogpkXGpauvyTO+dJrqb2rDJ2OZlfHgXhCbWXlyq6CPFmmwqly5ZtJMDyOLhUZ/yJ2z4e/vLJYFuEcOFk4BQrpmnsAiVsCZyV9WGZER5mR11Wri0kWBw0Nya/mbGljAYWJzB8PcpUvZcwa3/Zoh6WgYzoSeAKWP8ftQvcHOQIa7XrFUWWYGH9DpHFJ4f2TnLb+azIMeFkdLXRTO0wETkf3G1H8uSND7B95tHn4L77wcXe5lHTguj4vFHs3dy+o+sqRKqilB6et/ehikfinAh6aBg2isbVnnp5BFzvfwwPKEMb1bKfMpFB3xg9ip8qsVKN6t3Igx5ur8E6ZQ/GpQ4IBUqFc/gkj3cA4v+inA/x/J4Al3RB2kw5V3Jm0Nq9cDf7pUY9AGOoTWZz+TOGKXCrctWBRolCLBmJRKMBGcPCZd7WgCTU3dMzqb4MB8e86QBVNQO8rAr1Nb4IQIcohAthGaFScD0VmWv1/omL0GxIvFY+tNl0IT9OK0rF9pAM+LjuCzP56MeMpEQx+K5LR8sUQtN9QXcHaQfmkBv8ThPmQGkyRKM7t6Pimf9j1niiUp3HArtIFCKFTzYpPEXHc0LeAYLr7TQ06zlLuQLsOcHsIim/0aNAjyXVUFcVvNX673sKA6wvaAMLdJOAzea54U+MVOgeP1t2WTJGjr7TiUKm8SWxVy0OhxRKyjFtJPGktUCYA/4h0oNtVb1atSBBGfcbtt6RubdtQzGfYGjjJHSc329dS17AgoCdlyu1FllcJ3MqGya6LySxBN29Jh9qM9N5Qw3cnvvkkhG/f0yj44Vcna3MjxS4gobAFa5jZacxQ8w0xGRkjETfN/22Kt7qUZnKwQ5f21iMeTDXDtNwN/Pld866Z9GVBQKekM6J9AhR0kWVZJQJ`,
};

export const cardUrlMain = "https://jmdapi.com/tablevideo/?id=";
export const liveStreamCricketPageUrl =
  "https://maxbet07.com/liveStreamCricket/";
export const liveStreamUrlCricket = "https://maxbet07.com/liveStreamCricket/";
export const liveStreamUrl = "https://maxbet07.com/liveStream/";

export const teamStatus = {
  suspended: "suspended",
  active: "active",
  closed: "closed",
  ballStart: "ball start",
  ballStop: "ball stop",
  ballRunning: "ball running",
};

export const matchBettingType = {
  matchOdd: "matchOdd",
  bookmaker: "bookmaker",
  bookmaker2: "bookmaker2",
  quickbookmaker1: "quickbookmaker1",
  quickbookmaker2: "quickbookmaker2",
  quickbookmaker3: "quickbookmaker3",
  tiedMatch1: "tiedMatch1",
  tiedMatch2: "tiedMatch2",
  tiedMatch3: "tiedMatch3",
  completeMatch: "completeMatch",
  completeMatch1: "completeMatch1",
  completeManual: "completeManual",
  other: "other",
  tournament: "tournament",
};
export const sessionBettingType = {
  session: "session",
  fancy1: "fancy1",
  overByOver: "overByover",
  ballByBall: "ballByBall",
  oddEven: "oddEven",
  cricketCasino: "cricketCasino",
  tournament: "tournament",
};

export const profitLossDataForMatchConstants = {
  [matchBettingType.matchOdd]: {
    A: "teamARate",
    B: "teamBRate",
    C: "teamCRate",
  },
  [matchBettingType.bookmaker]: {
    A: "teamARate",
    B: "teamBRate",
    C: "teamCRate",
  },
  [matchBettingType.bookmaker2]: {
    A: "teamARate",
    B: "teamBRate",
    C: "teamCRate",
  },
  [matchBettingType.quickbookmaker1]: {
    A: "teamARate",
    B: "teamBRate",
    C: "teamCRate",
  },
  [matchBettingType.quickbookmaker2]: {
    A: "teamARate",
    B: "teamBRate",
    C: "teamCRate",
  },
  [matchBettingType.quickbookmaker3]: {
    A: "teamARate",
    B: "teamBRate",
    C: "teamCRate",
  },
  [matchBettingType.tiedMatch1]: {
    A: "yesRateTie",
    B: "noRateTie",
  },
  [matchBettingType.tiedMatch2]: {
    A: "yesRateTie",
    B: "noRateTie",
  },
  [matchBettingType.tiedMatch3]: {
    A: "yesRateTie",
    B: "noRateTie",
  },
  [matchBettingType.completeMatch]: {
    A: "yesRateComplete",
    B: "noRateComplete",
  },
  [matchBettingType.completeMatch1]: {
    A: "yesRateComplete",
    B: "noRateComplete",
  },
  [matchBettingType.completeManual]: {
    A: "yesRateComplete",
    B: "noRateComplete",
  },
  [matchBettingType.other]: {
    A: "userTeamARateOther",
    B: "userTeamBRateOther",
    C: "userTeamCRateOther",
  },
};

export const serviceUrl = import.meta.env.VITE_BASE_URL;

export const baseUrls = {
  socket: import.meta.env.VITE_BASE_URL,
  matchSocket: import.meta.env.VITE_THIRD_PARTY_BASE_URL,
  expertSocket: import.meta.env.VITE_EXPERT_BASE_URL,
};

export const marketApiConst: { [key: string]: string } = {
  cricket: ApiConstants.MATCH.MARKET_MATCH_LIST_CRICKET,
  football: ApiConstants.MATCH.MARKET_MATCH_LIST_FOOTBALL,
  tennis: ApiConstants.MATCH.MARKET_MATCH_LIST_TENNIS,
};

export const liveCasinoPics: any = {
  All: "https://tezcdn.io/casino/int-casino-icon/all.webp",
  "dragon tiger": "https://tezcdn.io/casino/int-casino-icon/dragon-tiger.webp",
  baccarat: "https://tezcdn.io/casino/int-casino-icon/baccarat.webp",
  sicbo: "https://tezcdn.io/casino/int-casino-icon/sicbo.webp",
  roulette: "https://tezcdn.io/casino/int-casino-icon/roulette.webp",
  poker: "https://tezcdn.io/casino/int-casino-icon/poker.webp",
  lucky7: "https://tezcdn.io/casino/int-casino-icon/lucky7.webp",
  andarbahar: "https://tezcdn.io/casino/int-casino-icon/andarbahar.webp",
  teenpatti: "https://tezcdn.io/casino/int-casino-icon/teenpatti.webp",
  "32cards": "https://tezcdn.io/casino/int-casino-icon/32cards.webp",
  others: "https://tezcdn.io/casino/int-casino-icon/others.webp",
  lottery: "https://tezcdn.io/casino/int-casino-icon/lottery.webp",
  cricketwar: "https://tezcdn.io/casino/int-casino-icon/cricketwar.webp",
  "hi low": "https://tezcdn.io/casino/int-casino-icon/hi-low.webp",
  "fun games": "https://tezcdn.io/casino/int-casino-icon/fun-games.webp",
  crash: "https://tezcdn.io/casino/int-casino-icon/crash.webp",
  aviator: "https://tezcdn.io/casino/int-casino-icon/aviator.webp",
  mines: "https://tezcdn.io/casino/int-casino-icon/mines.webp",
  slots: "https://tezcdn.io/casino/int-casino-icon/slots.webp",
  "live game show":
    "https://tezcdn.io/casino/int-casino-icon/live-game-show.webp",
  "color prediction":
    "https://tezcdn.io/casino/int-casino-icon/color-prediction.webp",
  "sic bo": "https://tezcdn.io/casino/int-casino-icon/sic-bo.webp",
  "bac bo": "https://tezcdn.io/casino/int-casino-icon/bac-bo.webp",
  "fan tan": "https://tezcdn.io/casino/int-casino-icon/fan-tan.webp",
  craps: "https://tezcdn.io/casino/int-casino-icon/craps.webp",
  blackjack: "https://tezcdn.io/casino/int-casino-icon/blackjack.webp",
  "casino holdem":
    "https://tezcdn.io/casino/int-casino-icon/casino-holdem.webp",
  "double hand casino holdem poker":
    "https://tezcdn.io/casino/int-casino-icon/double-hand-casino-holdem-poker.webp",
  "video poker": "https://tezcdn.io/casino/int-casino-icon/video-poker.webp",
  "extreme texas holdem":
    "https://tezcdn.io/casino/int-casino-icon/extreme-texas-holdem.webp",
  "triple card poker":
    "https://tezcdn.io/casino/int-casino-icon/triple-card-poker.webp",
};

export const liveCasinoGameList: any = [
  {
    game_id: "150063",
    game_name: "Dream Wheel",
    category: "live game show",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/dw.webp",
    game_code: "MAC88-YLGS101",
  },
  {
    game_id: "150046",
    game_name: "Cricket Match 20-20",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/cricket2020.webp",
    game_code: "MAC88-XCM101",
  },
  {
    game_id: "150637",
    game_name: "Cricket Match 20-20",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/cm.webp",
    game_code: "ME-BCM101",
  },
  {
    game_id: "150001",
    game_name: "Dragon Tiger",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/dt_mac88.webp",
    game_code: "MAC88-YDT102",
  },
  {
    game_id: "150013",
    game_name: "DTL",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/dtl_20_20.webp",
    game_code: "MAC88-YDTL101",
  },
  {
    game_id: "150036",
    game_name: "1 Day Dragon Tiger",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/dt_1day.webp",
    game_code: "MAC88-X1DT101",
  },
  {
    game_id: "150067",
    game_name: "Dragon Tiger 2",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/dt2.webp",
    game_code: "MAC88-DT2101",
  },
  {
    game_id: "150600",
    game_name: "Dragon Tiger",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/dt.webp",
    game_code: "ME-BDT101",
  },
  {
    game_id: "150609",
    game_name: "Dragon Tiger Lion",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/dtl.webp",
    game_code: "ME-BDTL101",
  },
  {
    game_id: "150628",
    game_name: "1 Day Dragon Tiger",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/dt1d.webp",
    game_code: "ME-B1DT101",
  },
  {
    game_id: "150646",
    game_name: "Dragon Tiger 2",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/dt2.webp",
    game_code: "ME-BDT2101",
  },
  {
    game_id: "150041",
    game_name: "6 Player Poker",
    category: "Poker",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/6pp.webp",
    game_code: "MAC88-X6PP101",
  },
  {
    game_id: "150005",
    game_name: "Poker 20-20",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/20_20_poker.webp",
    game_code: "MAC88-XPOK101",
  },
  {
    game_id: "150032",
    game_name: "Poker 1-Day",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/poker_1_day.webp",
    game_code: "MAC88-Y1POK101",
  },
  {
    game_id: "150604",
    game_name: "Poker 20-20",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/2020poker.webp",
    game_code: "ME-BPOK101",
  },
  {
    game_id: "150624",
    game_name: "Poker 1-Day",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/1dpoker.webp",
    game_code: "ME-B1POK101",
  },
  {
    game_id: "150633",
    game_name: "6 Player Poker",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/6pp.webp",
    game_code: "ME-B6PP101",
  },
  {
    game_id: "150056",
    game_name: "Instant Teen Patti",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/itp.webp",
    game_code: "MAC88-ZITP101",
  },

  {
    game_id: "150070",
    game_name: "AK47 Teenpatti",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/ak47tp.webp",
    game_code: "MAC88-XAK47101",
  },
  {
    game_id: "150054",
    game_name: "Muflis Teenpatti",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/mtp.webp",
    game_code: "MAC88-ZMTP101",
  },
  {
    game_id: "150066",
    game_name: "20 20 Teenpatti 2",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/2020tp2.webp",
    game_code: "MAC88-TPTT2101",
  },
  {
    game_id: "150009",
    game_name: "Teenpatti One Day",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/tp1d.webp",
    game_code: "MAC88-X1TP101",
  },
  {
    game_id: "150023",
    game_name: "Test Teenpatti",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/teenpatti_test.webp",
    game_code: "MAC88-YTTP102",
  },
  {
    game_id: "150042",
    game_name: "Instant 2 Cards Teenpatti",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/2_card_tp.webp",
    game_code: "MAC88-X2TP101",
  },
  {
    game_id: "150030",
    game_name: "Muflis Teenpatti 1 Day",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/muflis_teenpati.webp",
    game_code: "MAC88-Y1MTP101",
  },
  {
    game_id: "150033",
    game_name: "20-20 Teenpatti",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/20_20_teenpatti.webp",
    game_code: "MAC88-YTPTT101",
  },
  {
    game_id: "150028",
    game_name: "Two Card Teenpatti",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/2_cards_teenpatti.webp",
    game_code: "MAC88-Y12TP101",
  },
  {
    game_id: "150049",
    game_name: "Open Teen patti",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/open_teen_patti.webp",
    game_code: "MAC88-YOTP101",
  },
  {
    game_id: "150607",
    game_name: "Teenpatti One Day",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/tp1d.webp",
    game_code: "ME-B1TP101",
  },
  {
    game_id: "150617",
    game_name: "Test Teenpatti",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/ttp.webp",
    game_code: "ME-BTTP102",
  },
  {
    game_id: "150621",
    game_name: "Two Card Teenpatti",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/2ctp.webp",
    game_code: "ME-B12TP101",
  },
  {
    game_id: "150622",
    game_name: "Muflis Teenpatti One Day",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/mtp1d.webp",
    game_code: "ME-B1MTP101",
  },
  {
    game_id: "150625",
    game_name: "20-20 Teenpatti",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/2020tp.webp",
    game_code: "ME-BTPTT101",
  },
  {
    game_id: "150634",
    game_name: "Instant 2 Cards Teenpatti",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/instant_2ctp.webp",
    game_code: "ME-B2TP101",
  },
  {
    game_id: "150640",
    game_name: "Open Teen patti",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/otp.webp",
    game_code: "ME-BOTP101",
  },
  {
    game_id: "150645",
    game_name: "20 20 Teenpatti 2",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/2020tp2.webp",
    game_code: "ME-BTPTT2101",
  },
  {
    game_id: "150647",
    game_name: "Muflis Teenpatti",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/mtp.webp",
    game_code: "ME-BMTP101",
  },
  {
    game_id: "150649",
    game_name: "AK47 Teenpatti",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/ak47tp.webp",
    game_code: "ME-BAK47101",
  },
  {
    game_id: "150057",
    game_name: "Andar Bahar 50",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/ab50.webp",
    game_code: "MAC88-ZABL101",
  },
  {
    game_id: "150007",
    game_name: "Andar Bahar",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/andar_bahar.webp",
    game_code: "MAC88-XAB101",
  },
  {
    game_id: "150606",
    game_name: "Andar Bahar",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/ab.webp",
    game_code: "ME-BAB101",
  },
  {
    game_id: "150656",
    game_name: "Andar Bahar 50",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/ab50.webp",
    game_code: "ME-BABL101",
  },
  {
    game_id: "150068",
    game_name: "Lucky 5",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/lucky5.webp",
    game_code: "MAC88-XLK5101",
  },
  {
    game_id: "150006",
    game_name: "Lucky7",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/lucky_7.webp",
    game_code: "MAC88-YLK7101",
  },
  {
    game_id: "150605",
    game_name: "Lucky 7",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/l7.webp",
    game_code: "ME-BLK7101",
  },
  {
    game_id: "150651",
    game_name: "Lucky 5",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/lucky5.webp",
    game_code: "ME-BLK5101",
  },
  {
    game_id: "150002",
    game_name: "Bacarrat",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/baccarat_mac88.webp",
    game_code: "MAC88-XBAC101",
  },
  {
    game_id: "150026",
    game_name: "29 Baccarat",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/29b.webp",
    game_code: "MAC88-X29BC101",
  },
  {
    game_id: "150601",
    game_name: "Baccarat",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/baccarat.webp",
    game_code: "ME-BBAC101",
  },
  {
    game_id: "150620",
    game_name: "29 Baccarat",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/29b.webp",
    game_code: "ME-B29BC101",
  },
  {
    game_id: "150643",
    game_name: "Baccarat One Day",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/b1d.webp",
    game_code: "ME-B1BAC101",
  },
  {
    game_id: "150016",
    game_name: "Queen Race",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/queen.webp",
    game_code: "MAC88-YQR102",
  },
  {
    game_id: "150612",
    game_name: "Queen Race",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/queen.webp",
    game_code: "ME-BQR102",
  },
  {
    game_id: "150017",
    game_name: "Race 20",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/race_20.webp",
    game_code: "MAC88-YRTT102",
  },
  {
    game_id: "150613",
    game_name: "Race 20",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/r20.webp",
    game_code: "ME-BRTT102",
  },
  {
    game_id: "150043",
    game_name: "Race to 17",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/race_17.webp",
    game_code: "MAC88-XRT17101",
  },
  {
    game_id: "150635",
    game_name: "Race to 17",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/race17.webp",
    game_code: "ME-BRT17101",
  },
  {
    game_id: "150048",
    game_name: "Race to 2nd",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/race_2.webp",
    game_code: "MAC88-X1RTS101",
  },
  {
    game_id: "150639",
    game_name: "Race to 2nd",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/race2.webp",
    game_code: "ME-B1RTS101",
  },
  {
    game_id: "150059",
    game_name: "Center card",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/cc.webp",
    game_code: "MAC88-ZCC101",
  },

  {
    game_id: "150050",
    game_name: "Center Card One Day",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/center_card_one_day.webp",
    game_code: "MAC88-Y1CC101",
  },
  {
    game_id: "150650",
    game_name: "Center Card",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/cc.webp",
    game_code: "ME-BCC101",
  },
  {
    game_id: "150641",
    game_name: "Center Card One Day",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/cc1d.webp",
    game_code: "ME-B1CC101",
  },

  {
    game_id: "150003",
    game_name: "Sic Bo",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/sicbo_mac88.webp",
    game_code: "MAC88-XSB101",
  },
  {
    game_id: "150602",
    game_name: "Sic Bo",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/sb.webp",
    game_code: "ME-BSB101",
  },
  {
    game_id: "150051",
    game_name: "High Low",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/high_low.webp",
    game_code: "MAC88-YHL101",
  },
  {
    game_id: "150642",
    game_name: "High Low",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/hl.webp",
    game_code: "ME-BHL101",
  },
  {
    game_id: "150058",
    game_name: "Super Over",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/so.webp",
    game_code: "MAC88-ZSP101",
  },
  {
    game_id: "150654",
    game_name: "Instant Super Over",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/iso.webp",
    game_code: "ME-BSP101",
  },
  {
    game_id: "150020",
    game_name: "Lottery",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/lottery.webp",
    game_code: "MAC88-XLOT101",
  },
  {
    game_id: "150616",
    game_name: "Lottery",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/lottery.webp",
    game_code: "ME-BLOT101",
  },

  {
    game_id: "150061",
    game_name: "Side Bet city",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/sbc.webp",
    game_code: "MAC88-ZSBC101",
  },
  {
    game_id: "150652",
    game_name: "Side Bet City",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/sbc.webp",
    game_code: "ME-BSBC101",
  },
  {
    game_id: "150019",
    game_name: "Worli Matka",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/worli_matka.webp",
    game_code: "MAC88-YWM102",
  },
  {
    game_id: "150055",
    game_name: "Instant worli",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/iw.webp",
    game_code: "MAC88-ZIW101",
  },
  {
    game_id: "150653",
    game_name: "Instant Worli",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/iw.webp",
    game_code: "ME-BIW101",
  },
  {
    game_id: "150004",
    game_name: "Roulette",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/roulette_mac88.webp",
    game_code: "MAC88-XRT101",
  },
  {
    game_id: "150603",
    game_name: "Roulette",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/roulette.webp",
    game_code: "ME-BRT101",
  },

  {
    game_id: "150014",
    game_name: "Amar Akbar Anthony",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/amar_akbar_anthony.webp",
    game_code: "MAC88-YA3101",
  },
  {
    game_id: "150610",
    game_name: "Amar Akbar Anthony",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/aaa.webp",
    game_code: "ME-BA3101",
  },
  {
    game_id: "150015",
    game_name: "3 Cards Judgement",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/3cj.webp",
    game_code: "MAC88-X3CJ101",
  },
  {
    game_id: "150611",
    game_name: "3 Cards Judgement",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/3cj.webp",
    game_code: "ME-B3CJ101",
  },
  {
    game_id: "150018",
    game_name: "Casino War",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/casino_war.webp",
    game_code: "MAC88-XCAW101",
  },
  {
    game_id: "150614",
    game_name: "Casino War",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/cw.webp",
    game_code: "ME-BCAW101",
  },

  {
    game_id: "150025",
    game_name: "Trio",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/trio.webp",
    game_code: "MAC88-XTRI101",
  },
  {
    game_id: "150619",
    game_name: "Trio",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/trio.webp",
    game_code: "ME-BTRI101",
  },
  {
    game_id: "150031",
    game_name: "Bollywood Casino B",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/bollywood_casino.webp",
    game_code: "MAC88-YBOC102",
  },
  {
    game_id: "150623",
    game_name: "Bollywood Casino",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/bc.webp",
    game_code: "ME-BBOC102",
  },
  {
    game_id: "150037",
    game_name: "Dus Ka Dum",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/10kadum.webp",
    game_code: "MAC88-X1DKD101",
  },
  {
    game_id: "150629",
    game_name: "Dus Ka Dum",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/dkd.webp",
    game_code: "ME-B1DKD101",
  },
  {
    game_id: "150040",
    game_name: "One Card One Day",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/1c1d.webp",
    game_code: "MAC88-X10C101",
  },
  {
    game_id: "150648",
    game_name: "One Card One Day",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/1c1d.webp",
    game_code: "ME-B1OC101",
  },
  {
    game_id: "150045",
    game_name: "Note Number",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/notenumber.webp",
    game_code: "MAC88-X1NN101",
  },
  {
    game_id: "150636",
    game_name: "Note Number",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/nn.webp",
    game_code: "ME-B1NN101",
  },
  {
    game_id: "150053",
    game_name: "10 - 10 cricket ",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/10_10_cricket.webp",
    game_code: "MAC88-YXC101",
  },
  {
    game_id: "150010",
    game_name: "32 Cards",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/32_cards.webp",
    game_code: "MAC88-Y32CA102",
  },
  {
    game_id: "150657",
    game_name: "FootBall Studio Dice",
    category: "Game Shows",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/fsd.webp",
    game_code: "ME-BFBS101",
  },
  {
    game_id: "150630",
    game_name: "One Card 20 20",
    category: "Live",
    provider_name: "MAC Excite",
    sub_provider_name: "MAC Excite",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/macexcite/1c.webp",
    game_code: "ME-BCTT101",
  },

  {
    game_id: "151083",
    game_name: "Ball by Ball VR",
    category: "Virtual",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming Virtual",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/bbb.webp",
    game_code: "MAC88-BB101",
  },
  {
    game_id: "151081",
    game_name: "Lucky 15",
    category: "Virtual",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming Virtual",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/lucky15.webp",
    game_code: "MAC88-L15101",
  },
  {
    game_id: "151026",
    game_name: "Lankesh",
    category: "Live",
    provider_name: "MAC88",
    sub_provider_name: "Mac88 Gaming Virtual",
    status: "ACTIVE",
    url_thumb: "https://cdn.dreamdelhi.com/mac88/lankesh.jpeg",
    game_code: "MAC88-VTGLN101",
  },
];

export const homeCasinoListIcons: any = {
  aviator: "https://tezcdn.io/casino/casino-highlight/aviator-730-280.gif",
  mines: "https://tezcdn.io/casino/casino-highlight/evoplay-730-280.gif",
  "fun games": "https://tezcdn.io/casino/casino-highlight/fungames-730_280.gif",
  "color prediction":
    "https://tezcdn.io/casino/casino-highlight/wingogames-730-280.gif",
};
